export const $ = id => document.getElementById(id);

export const dom = {
  searchInput:    $('entity-search'),
  searchResults:  $('search-results'),
  relationSection: $('relation-section'),
  relationSearch: $('relation-search'),
  relationList:   $('relation-list'),
  predictBtn:     $('predict-btn'),
  selectionDisp:  $('selection-display'),
  chipHead:       $('chip-head'),
  chipRel:        $('chip-rel'),
  graphTitle:     $('graph-title'),
  predictSection: $('predict-section'),
  predictPlaceh:  $('predict-placeholder'),
  predictList:    $('predict-list'),
  explainPlaceh:  $('explain-placeholder'),
  explainContent: $('explain-content'),
  explainSummary: $('explain-summary'),
  influenceList:  $('influence-list'),
  explainBottom:  $('explain-bottom'),
  explainCloseBtn: $('explain-drawer-close'),
  resetBtn:       $('reset-btn'),
  statusDot:      $('status-dot'),
  statusText:     $('status-text'),
  tooltip:        $('graph-tooltip'),
  explorerView:   $('explorer-view'),

  // Training UI references
  navBtns:        document.querySelectorAll('.nav-btn'),
  views:          document.querySelectorAll('.view-section'),
  modelSelect:    $('model-select'),
  deleteModelBtn: $('delete-model-btn'),
  trainNameInput: $('train-model-name'),
  trainFileInput: $('train-file-upload'),
  trainMappingInput: $('train-mapping-upload'),
  trainStartBtn:  $('train-start-btn'),
  trainProgArea:  $('training-progress-area'),
  trainStatusTxt: $('train-status-text'),
  trainEpochTxt:  $('train-epoch-text'),
  trainProgBar:   $('train-progress-bar'),
  metricLoss:     $('metric-loss'),
  trainLog:       $('train-log')
};
